/**
 * The canon data layer. Pure data import — no I/O, no adapters, safe to
 * bundle into any JS runtime (browser, React Native, Node test runner).
 * The JSON itself is generated by /scripts/ingest-canon.ts from the seed
 * files under /scripts/seed; this module just types and re-exports it.
 */
import housesJson from "@data/houses.json";
import wandsJson from "@data/wands.json";
import spellsJson from "@data/spells.json";
import charactersJson from "@data/characters.json";
import timelineJson from "@data/timeline.json";
import locationsJson from "@data/locations.json";
import creaturesJson from "@data/creatures.json";
import subjectsJson from "@data/subjects.json";
import bloodStatusJson from "@data/bloodStatus.json";
import factionsJson from "@data/factions.json";

import type {
  BloodStatusEntry,
  CanonDataBundle,
  CanonCharacter,
  Creature,
  Faction,
  House,
  Location,
  Spell,
  Subject,
  TimelineEvent,
  WandData,
} from "./types.js";

export const canonData: CanonDataBundle = {
  houses: housesJson as House[],
  wands: wandsJson as WandData,
  spells: spellsJson as Spell[],
  characters: charactersJson as CanonCharacter[],
  timeline: timelineJson as TimelineEvent[],
  locations: locationsJson as Location[],
  creatures: creaturesJson as Creature[],
  subjects: subjectsJson as Subject[],
  bloodStatuses: bloodStatusJson as BloodStatusEntry[],
  factions: factionsJson as Faction[],
};

export function getHouse(id: string): House | undefined {
  return canonData.houses.find((h) => h.id === id);
}

export function getCharacter(id: string): CanonCharacter | undefined {
  return canonData.characters.find((c) => c.id === id);
}

export function getSpell(id: string): Spell | undefined {
  return canonData.spells.find((s) => s.id === id);
}

export function getSubject(id: string): Subject | undefined {
  return canonData.subjects.find((s) => s.id === id);
}
