import type { Spell } from "../../core/src/data/types.js";

/**
 * "year" in firstCanonicalAppearance is the in-story Hogwarts year the
 * spell is first shown or named on the page (1991 = Philosopher's Stone's
 * story year, 1997 = Deathly Hallows'), which is what the era/canon
 * validator needs. It is not the real-world publication year.
 */
export const spells: Spell[] = [
  {
    id: "wingardium-leviosa",
    incantation: "Wingardium Leviosa",
    effect: "Levitates and moves a target object.",
    type: "charm",
    difficulty: "simple",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Philosopher's Stone", year: 1991 },
    wandMovement: "swish and flick",
    canonTier: "book",
    source: "Philosopher's Stone, ch. 10",
  },
  {
    id: "alohomora",
    incantation: "Alohomora",
    effect: "Unlocks doors and other locked objects.",
    type: "charm",
    difficulty: "simple",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Philosopher's Stone", year: 1991 },
    wandMovement: null,
    canonTier: "book",
    source: "Philosopher's Stone, ch. 9",
  },
  {
    id: "lumos",
    incantation: "Lumos",
    effect: "Lights the tip of the caster's wand.",
    type: "charm",
    difficulty: "simple",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Philosopher's Stone", year: 1991 },
    wandMovement: null,
    canonTier: "book",
    source: "Philosopher's Stone, ch. 16",
  },
  {
    id: "nox",
    incantation: "Nox",
    effect: "Extinguishes the light produced by Lumos.",
    type: "counter-spell",
    difficulty: "simple",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Chamber of Secrets", year: 1992 },
    wandMovement: null,
    canonTier: "book",
    source: "Chamber of Secrets",
  },
  {
    id: "expelliarmus",
    incantation: "Expelliarmus",
    effect: "Disarms an opponent, knocking the wand from their hand.",
    type: "charm",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Chamber of Secrets", year: 1992 },
    wandMovement: null,
    canonTier: "book",
    source: "Chamber of Secrets, ch. 11 (Duelling Club)",
  },
  {
    id: "petrificus-totalus",
    incantation: "Petrificus Totalus",
    effect: "Full Body-Bind: locks the target's limbs rigidly together.",
    type: "curse",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Philosopher's Stone", year: 1991 },
    wandMovement: null,
    canonTier: "book",
    source: "Philosopher's Stone, ch. 16",
  },
  {
    id: "locomotor-mortis",
    incantation: "Locomotor Mortis",
    effect: "Leg-Locker Curse: binds the target's legs together.",
    type: "curse",
    difficulty: "simple",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Philosopher's Stone", year: 1991 },
    wandMovement: null,
    canonTier: "book",
    source: "Philosopher's Stone, ch. 9",
  },
  {
    id: "rictusempra",
    incantation: "Rictusempra",
    effect: "Tickling Charm: doubles the target over with uncontrollable laughter.",
    type: "charm",
    difficulty: "simple",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Chamber of Secrets", year: 1992 },
    wandMovement: null,
    canonTier: "book",
    source: "Chamber of Secrets, ch. 11 (Duelling Club)",
  },
  {
    id: "serpensortia",
    incantation: "Serpensortia",
    effect: "Conjures a snake from the caster's wand.",
    type: "transfiguration",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Chamber of Secrets", year: 1992 },
    wandMovement: null,
    canonTier: "book",
    source: "Chamber of Secrets, ch. 11 (Duelling Club)",
  },
  {
    id: "obliviate",
    incantation: "Obliviate",
    effect: "Erases or alters specific memories in the target.",
    type: "charm",
    difficulty: "advanced",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Chamber of Secrets", year: 1992 },
    wandMovement: null,
    canonTier: "book",
    source: "Chamber of Secrets, ch. 16 (Lockhart's failed attempt)",
  },
  {
    id: "riddikulus",
    incantation: "Riddikulus",
    effect: "Forces a Boggart to take a less frightening, ridiculous form.",
    type: "charm",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Prisoner of Azkaban", year: 1993 },
    wandMovement: null,
    canonTier: "book",
    source: "Prisoner of Azkaban, ch. 7",
  },
  {
    id: "expecto-patronum",
    incantation: "Expecto Patronum",
    effect: "Conjures a Patronus to repel Dementors and Lethifolds.",
    type: "charm",
    difficulty: "advanced",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Prisoner of Azkaban", year: 1993 },
    wandMovement: null,
    canonTier: "book",
    source: "Prisoner of Azkaban, ch. 12",
  },
  {
    id: "avada-kedavra",
    incantation: "Avada Kedavra",
    effect: "The Killing Curse: causes instant death with no known counter-curse.",
    type: "curse",
    difficulty: "advanced",
    isUnforgivable: true,
    firstCanonicalAppearance: { book: "Goblet of Fire", year: 1994 },
    wandMovement: null,
    canonTier: "book",
    source: "Goblet of Fire, ch. 1 & 34",
  },
  {
    id: "crucio",
    incantation: "Crucio",
    effect: "The Cruciatus Curse: inflicts excruciating pain on the target.",
    type: "curse",
    difficulty: "advanced",
    isUnforgivable: true,
    firstCanonicalAppearance: { book: "Goblet of Fire", year: 1994 },
    wandMovement: null,
    canonTier: "book",
    source: "Goblet of Fire, ch. 14",
  },
  {
    id: "imperio",
    incantation: "Imperio",
    effect: "The Imperius Curse: places the target under the caster's total control.",
    type: "curse",
    difficulty: "advanced",
    isUnforgivable: true,
    firstCanonicalAppearance: { book: "Goblet of Fire", year: 1994 },
    wandMovement: null,
    canonTier: "book",
    source: "Goblet of Fire, ch. 14",
  },
  {
    id: "accio",
    incantation: "Accio",
    effect: "The Summoning Charm: pulls a named object to the caster.",
    type: "charm",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Goblet of Fire", year: 1994 },
    wandMovement: null,
    canonTier: "book",
    source: "Goblet of Fire, ch. 20 (first Triwizard task)",
  },
  {
    id: "protego",
    incantation: "Protego",
    effect: "The Shield Charm: deflects incoming curses and jinxes.",
    type: "charm",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Goblet of Fire", year: 1994 },
    wandMovement: null,
    canonTier: "book",
    source: "Goblet of Fire",
  },
  {
    id: "finite-incantatem",
    incantation: "Finite Incantatem",
    effect: "A general counter-spell that halts ongoing spell effects.",
    type: "counter-spell",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Chamber of Secrets", year: 1992 },
    wandMovement: null,
    canonTier: "book",
    source: "Chamber of Secrets, ch. 11",
  },
  {
    id: "stupefy",
    incantation: "Stupefy",
    effect: "The Stunning Spell: renders the target unconscious.",
    type: "charm",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Order of the Phoenix", year: 1995 },
    wandMovement: null,
    canonTier: "book",
    source: "Order of the Phoenix (Dumbledore's Army lessons)",
  },
  {
    id: "reducto",
    incantation: "Reducto",
    effect: "The Reductor Curse: blasts a solid object apart.",
    type: "curse",
    difficulty: "advanced",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Order of the Phoenix", year: 1995 },
    wandMovement: null,
    canonTier: "book",
    source: "Order of the Phoenix",
  },
  {
    id: "diffindo",
    incantation: "Diffindo",
    effect: "The Severing Charm: cuts the object it is aimed at.",
    type: "charm",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Order of the Phoenix", year: 1995 },
    wandMovement: null,
    canonTier: "book",
    source: "Order of the Phoenix",
  },
  {
    id: "legilimens",
    incantation: "Legilimens",
    effect: "Allows the caster to enter and navigate the target's mind.",
    type: "spell",
    difficulty: "advanced",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Order of the Phoenix", year: 1995 },
    wandMovement: null,
    canonTier: "book",
    source: "Order of the Phoenix, ch. 24 (Occlumency lessons)",
  },
  {
    id: "sectumsempra",
    incantation: "Sectumsempra",
    effect: "Inflicts deep, slashing wounds as if by an invisible sword.",
    type: "curse",
    difficulty: "newt-level",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Half-Blood Prince", year: 1996 },
    wandMovement: null,
    canonTier: "book",
    source: "Half-Blood Prince, ch. 24. Invented by Severus Snape ('For Enemies').",
  },
  {
    id: "muffliato",
    incantation: "Muffliato",
    effect: "Fills the ears of anyone nearby with an unidentifiable buzzing, to prevent eavesdropping.",
    type: "charm",
    difficulty: "advanced",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Half-Blood Prince", year: 1996 },
    wandMovement: null,
    canonTier: "book",
    source: "Half-Blood Prince, ch. 12. Invented by Severus Snape.",
  },
  {
    id: "levicorpus",
    incantation: "Levicorpus",
    effect: "Hoists the target into the air by the ankle.",
    type: "jinx",
    difficulty: "advanced",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Half-Blood Prince", year: 1996 },
    wandMovement: null,
    canonTier: "book",
    source: "Half-Blood Prince, ch. 9. Invented by Severus Snape.",
  },
  {
    id: "episkey",
    incantation: "Episkey",
    effect: "Heals minor injuries such as a broken nose.",
    type: "charm",
    difficulty: "standard",
    isUnforgivable: false,
    firstCanonicalAppearance: { book: "Half-Blood Prince", year: 1996 },
    wandMovement: null,
    canonTier: "book",
    source: "Half-Blood Prince, ch. 10",
  },
];
