// Copies the root Vite build output (../dist) into ./www, which is what
// gets packaged into the Electron app (electron-builder's `files` config
// only reaches into the app directory itself, not a parent directory, so
// the built site needs to live inside /desktop before packaging). Not
// committed — regenerated by `npm run build` at the repo root + this
// script every time.
const fs = require("node:fs");
const path = require("node:path");

const distDir = path.join(__dirname, "..", "dist");
const wwwDir = path.join(__dirname, "www");

if (!fs.existsSync(distDir)) {
  console.error(
    "[desktop] ../dist doesn't exist yet — run `npm run build` at the repo root first."
  );
  process.exit(1);
}

fs.rmSync(wwwDir, { recursive: true, force: true });
fs.cpSync(distDir, wwwDir, { recursive: true });
console.log(`[desktop] copied ${distDir} -> ${wwwDir}`);
